/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}", "./public/index.html"],
  darkMode: "class",
  important: true,
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#c3c0ff",
        "on-primary-fixed-variant": "#3323cc",
        surface: "#f7f9fb",
        "on-error": "#ffffff",
        primary: "#3525cd",
        "on-secondary-container": "#fffbff",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#4f46e5",
        tertiary: "#005338",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-container": "#eceef0",
        "inverse-surface": "#2d3133",
        background: "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "tertiary-container": "#006e4b",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        secondary: "#b90538",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#dad7ff",
        "on-tertiary-container": "#67f4b7",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed-dim": "#ffb2b7",
        "on-surface-variant": "#464555",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#40000d",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#4edea3",
        "on-surface": "#191c1e",
        "surface-tint": "#4d44e3",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffdadb",
        "outline-variant": "#c7c4d8",
        outline: "#777587",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-container": "#dc2c4f",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#92002a",
        "on-primary-fixed": "#0f0069",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1rem",
        "stack-lg": "2rem",
        "container-max": "1280px",
        gutter: "1.5rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "section-gap": "4rem",
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-lg": ["Inter"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
